name: hcrseq
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Core bioinformatics tools
  - python=3.12
  - samtools=1.21
  - bwa=0.7.18
  - picard
  - cutadapt

  # Python libraries 
  - pip
  - h5py
  - hdf5=2.1.0
  - matplotlib~=3.8.3
  - seaborn~=0.13.2
  - numpy~=1.26.4
  - pandas~=2.2.0
  - scipy~=1.12.0
  - pysam~=0.22.0
  - treelib~=1.7.0
  - biopython~=1.84
  - pyyaml~=6.0.1
  - setuptools~=68.2.2
  - click~=8.1.7
  - scanpy~=1.11.4
  - numba>=0.58.0
  - llvmlite>=0.41.0
  - parasail-python~=1.3.4
  - umi_tools~=1.1.6
